// import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import TopBanner  from './components/layout/Banner/TopBanner'
import Navbar from './components/layout/Navbar/TopNavbar'
import { RootContext } from './components/Context/RootContext'

const inter = Inter({ subsets: ['latin'] })


// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout( {children}:{children: React.ReactNode} ) {
  return (
    <html lang="en">
      <body className={inter.className}>
       <RootContext>
        <TopBanner/>
        <Navbar/>
        {children}
        </RootContext>
        </body>
    </html>
  )
}
